### ISSUE TITLE
Fix codegen error on rules that use certain ocaml keywords

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter-core#22]
I tried 
```
./add-simple-lang https://github.com/tree-sitter/tree-sitter-python.git
cd lang
./test-lang python
make[1]: Leaving directory '/home/pad/github/ocaml-tree-sitter-semgrep/lang/python'
make build-ocaml
make[1]: Entering directory '/home/pad/github/ocaml-tree-sitter-semgrep/lang/python'
/home/pad/github/ocaml-tree-sitter-semgrep/scripts/build-ocaml
File "lib/CST.ml", line 1113, characters 2-16:
1113 |   sexp_of_module root
         ^^^^^^^^^^^^^^
Error: Unbound value sexp_of_module
Hint: Did you mean sexp_of_module_?

```
I think the reason is that in grammar.js a rule is called 'module', which is an ocaml keyword,
and it's correctly handled when generating the type definition by suffixing the keyword with `_`,
but then when it comes to generate the code of the function `dump_tree` we still
use the original grammar rule `sexp_of_module` instead of `sexp_of_module_`.

**Comment by mjambon** [comment]
yes, that was the problem. I fixed it in #23 by calling the function that translates the rule name.
