### ISSUE TITLE
Blank nodes for token.immediate inside a repeat (for C and C++)

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter-core#38]
I've just tried to regenerate semgrep-c and semgrep-cpp but got an error about Blank nodes.

```
$ ./test-lang c
...
c: Checking for undesirable Blank nodes.
      | `DQUOT of Token.t (* "\"" *)
    ]
  * [ `Blank of unit (* blank *) | `Esc_seq of escape_sequence (*tok*) ]
      list (* zero or more *)
  * Token.t (* "\"" *)

found in /home/pad/github/ocaml-tree-sitter-semgrep/lang/c/ocaml-src/lib/CST.ml
language: c
```

Same for C++.

The problem seems to come from this grammar rule in tree-sitter-c/grammar.js:
```
 string_literal: $ => seq(
      choice('L"', 'u"', 'U"', 'u8"', '"'),
      repeat(choice(
        token.immediate(prec(1, /[^\\"\n]+/)),
        $.escape_sequence
      )),
      '"',
    ),
```

there is a similar one for chars, but it does not seem to cause problems:
```
    char_literal: $ => seq(
      choice('L\'', 'u\'', 'U\'', 'u8\'', '\''),
      choice(
        $.escape_sequence,
        token.immediate(/[^\n']/)
      ),
      '\''
    ),
```

**Comment by aryx** [comment]
I've tried an alias(token.immediage(...), $._stuff) but then
I actually get nodes in the CST about _stuff and this causes errors on the corpus tests.

What is weird is that in the semgrep-c/ and semgrep-cpp/ used inside semgrep, there is no Blank nodes but instead:
```
type string_literal = (
    [
        `LDQUOT of Token.t (* "L\"" *)
      | `UDQUOT_c163aae of Token.t (* "u\"" *)
      | `UDQUOT_df3447d of Token.t (* "U\"" *)
      | `U8DQUOT of Token.t (* "u8\"" *)
      | `DQUOT of Token.t (* "\"" *)
    ]
  * [
        `Imm_tok_pat_c7f65b4 of imm_tok_pat_c7f65b4 (*tok*)
      | `Esc_seq of escape_sequence (*tok*)
    ]
      list (* zero or more *)
  * Token.t (* "\"" *)
)
[@@deriving sexp_of]
```
so not sure if it's a regression recently introduced, or last time someone (me?) did some hack to go around those Blank nodes errors.

**Comment by mjambon** [comment]
I believe this problem is similar to #37 and could be fixed with a similar solution. I don't think there's a generic workaround available to the user.
