### ISSUE TITLE
Add support for `MISSING` nodes

### ISSUE THREAD

**Issue by mjambon** [returntocorp/ocaml-tree-sitter-core#8]
See https://github.com/returntocorp/semgrep/issues/1868#issuecomment-740089520

**Comment by aryx** [comment]
Maybe once you're done with the Blank issue you could fix this one @mjambon ?
This would help closing some old Ruby issues.

**Comment by mjambon** [comment]
added to my queue

**Comment by aryx** [comment]
still an issue

**Comment by mjambon** [comment]
The plan is to treat `MISSING` nodes like `ERROR` nodes:
* they indicate a problem in the target code
* they allow the rest of the file to be parsed correctly (hopefully)
* they should be reported but should be fatal only we care about the full correctness of the target code

**Comment by aryx** [comment]
sounds good to me.

**Comment by mjambon** [comment]
> got hit by this also here: [fwcd/tree-sitter-kotlin#25 (comment)](https://github.com/fwcd/tree-sitter-kotlin/pull/25#issuecomment-939138980) Basically we thought we were parsing correctly 90% of some codebase, but really it was 80% because the CST was wrong because tree-sitter was silently adding those MISSING nodes to try to makeup for some defects in the grammar.

Since a missing node has zero width, it will now count as one error line. It's less than the average error node which often spans multiple lines. The fraction of lines affected by errors is what we use to determine the parsing rate.
